import type {
  GuestProfile,
  Ingredient,
  MenuItem,
  Order,
  StaffMember,
  Table,
} from "./domain";

export const restaurant = {
  name: "Ember & Ash",
  shortName: "E&A",
  venue: "Fordham University, Lincoln Center, New York",
  serviceLabel: "Dinner service",
  covers: 86,
};

export const ingredients: Ingredient[] = [
  { id: "carrot", name: "Carrots", aliases: ["carrot", "carrots"], onHand: 3, par: 18, unit: "lb" },
  { id: "beet", name: "Golden beets", aliases: ["beet", "beets"], onHand: 16, par: 12, unit: "lb" },
  { id: "parsnip", name: "Parsnips", aliases: ["parsnip", "parsnips"], onHand: 14, par: 10, unit: "lb" },
  { id: "salmon", name: "Salmon", aliases: ["salmon", "fish"], onHand: 24, par: 30, unit: "portions" },
  { id: "chicken", name: "Chicken", aliases: ["chicken", "poultry"], onHand: 38, par: 36, unit: "portions" },
  { id: "farro", name: "Farro", aliases: ["farro", "grain"], onHand: 12, par: 8, unit: "lb" },
  { id: "hazelnut", name: "Hazelnuts", aliases: ["hazelnut", "nuts"], onHand: 5, par: 6, unit: "lb" },
  { id: "mushroom", name: "Mushrooms", aliases: ["mushroom", "mushrooms"], onHand: 15, par: 12, unit: "lb" },
  { id: "cauliflower", name: "Cauliflower", aliases: ["cauliflower"], onHand: 11, par: 9, unit: "heads" },
  { id: "beef", name: "Dry-aged beef", aliases: ["beef", "steak"], onHand: 8, par: 18, unit: "portions" },
  { id: "chocolate", name: "Dark chocolate", aliases: ["chocolate"], onHand: 10, par: 8, unit: "lb" },
];

export const menuItems: MenuItem[] = [
  {
    id: "carrot-tartare",
    name: "Charred Carrot Tartare",
    description: "Smoked carrot, rye crisp, hazelnut, mustard seed",
    section: "starter",
    ingredientIds: ["carrot", "hazelnut"],
    tags: ["vegetarian"],
    allergens: ["tree nuts", "gluten"],
    price: 18,
    prepMinutes: 8,
    popularity: 91,
    marginScore: 86,
  },
  {
    id: "beet-salad",
    name: "Golden Beet & Citrus",
    description: "Roasted golden beet, blood orange, dill, verjus",
    section: "starter",
    ingredientIds: ["beet"],
    tags: ["vegan", "vegetarian", "gluten-free"],
    allergens: [],
    price: 17,
    prepMinutes: 6,
    popularity: 84,
    marginScore: 90,
  },
  {
    id: "salmon-carrot",
    name: "Cedar Salmon",
    description: "Cedar-roasted salmon, carrot purée, charred leek",
    section: "main",
    ingredientIds: ["salmon", "carrot"],
    tags: ["gluten-free", "pescatarian"],
    allergens: ["fish"],
    price: 34,
    prepMinutes: 16,
    popularity: 94,
    marginScore: 72,
  },
  {
    id: "mushroom-farro",
    name: "Woodland Mushroom Farro",
    description: "Roasted mushrooms, farro, black garlic, pecorino",
    section: "main",
    ingredientIds: ["mushroom", "farro"],
    tags: ["vegetarian"],
    allergens: ["gluten", "dairy"],
    price: 29,
    prepMinutes: 13,
    popularity: 82,
    marginScore: 88,
  },
  {
    id: "herb-chicken",
    name: "Herb-Roasted Chicken",
    description: "Half chicken, parsnip, rosemary jus",
    section: "main",
    ingredientIds: ["chicken", "parsnip"],
    tags: ["gluten-free"],
    allergens: [],
    price: 32,
    prepMinutes: 18,
    popularity: 89,
    marginScore: 76,
  },
  {
    id: "ember-steak",
    name: "Ember Dry-Aged Steak",
    description: "Dry-aged strip, smoked onion, pepper jus",
    section: "main",
    ingredientIds: ["beef"],
    tags: ["gluten-free"],
    allergens: [],
    price: 48,
    prepMinutes: 22,
    popularity: 97,
    marginScore: 68,
  },
  {
    id: "cauliflower",
    name: "Coal-Roasted Cauliflower",
    description: "Tahini, preserved lemon, herb salad",
    section: "main",
    ingredientIds: ["cauliflower"],
    tags: ["vegan", "vegetarian", "gluten-free"],
    allergens: ["sesame"],
    price: 27,
    prepMinutes: 12,
    popularity: 86,
    marginScore: 93,
  },
  {
    id: "roasted-roots",
    name: "Ember-Roasted Roots",
    description: "Carrot, golden beet, parsnip, thyme",
    section: "side",
    ingredientIds: ["carrot", "beet", "parsnip"],
    tags: ["vegan", "vegetarian", "gluten-free"],
    allergens: [],
    price: 13,
    prepMinutes: 9,
    popularity: 78,
    marginScore: 91,
  },
  {
    id: "chocolate-torte",
    name: "Dark Chocolate Torte",
    description: "Bittersweet chocolate, olive oil, sea salt",
    section: "dessert",
    ingredientIds: ["chocolate"],
    tags: ["vegetarian", "gluten-free"],
    allergens: ["eggs"],
    price: 14,
    prepMinutes: 5,
    popularity: 92,
    marginScore: 89,
  },
];

export const staff: StaffMember[] = [
  { id: "host-1", name: "Ari Kim", role: "host", initials: "AK" },
  { id: "server-1", name: "Mina Cole", role: "server", initials: "MC", section: "main" },
  { id: "server-2", name: "Theo Grant", role: "server", initials: "TG", section: "window" },
  { id: "server-3", name: "Rosa Diaz", role: "server", initials: "RD", section: "patio" },
  { id: "manager-1", name: "Marcus Lee", role: "manager", initials: "ML" },
];

export const demoTables: Table[] = [
  { id: "t1", label: "T1", capacity: 2, area: "window", status: "available", accessible: true, serverId: "server-2", seatedGuestId: null, seatedAt: null, estimatedAvailableMinutes: 0 },
  { id: "t2", label: "T2", capacity: 4, area: "window", status: "available", accessible: true, serverId: "server-2", seatedGuestId: null, seatedAt: null, estimatedAvailableMinutes: 0 },
  { id: "t3", label: "T3", capacity: 4, area: "main", status: "occupied", accessible: true, serverId: "server-1", seatedGuestId: "guest-noah", seatedAt: "2026-08-09T21:35:00.000Z", estimatedAvailableMinutes: 54 },
  { id: "t4", label: "T4", capacity: 6, area: "main", status: "available", accessible: true, serverId: "server-1", seatedGuestId: null, seatedAt: null, estimatedAvailableMinutes: 0 },
  { id: "t5", label: "T5", capacity: 4, area: "main", status: "clearing", accessible: false, serverId: "server-1", seatedGuestId: null, seatedAt: null, estimatedAvailableMinutes: 8 },
  { id: "t6", label: "T6", capacity: 2, area: "bar", status: "available", accessible: false, serverId: "server-2", seatedGuestId: null, seatedAt: null, estimatedAvailableMinutes: 0 },
  { id: "t7", label: "T7", capacity: 4, area: "patio", status: "available", accessible: true, serverId: "server-3", seatedGuestId: null, seatedAt: null, estimatedAvailableMinutes: 0 },
  { id: "t8", label: "T8", capacity: 6, area: "patio", status: "reserved", accessible: true, serverId: "server-3", seatedGuestId: null, seatedAt: null, estimatedAvailableMinutes: 25 },
  { id: "t9", label: "T9", capacity: 8, area: "main", status: "available", accessible: true, serverId: "server-1", seatedGuestId: null, seatedAt: null, estimatedAvailableMinutes: 0 },
];

export const demoGuests: GuestProfile[] = [
  {
    id: "guest-maya",
    name: "Maya Chen",
    partySize: 4,
    reservationTime: "6:15 PM",
    arrivalTime: "6:07 PM",
    status: "waiting",
    allergies: ["tree nuts"],
    dietaryNeeds: ["gluten-free"],
    likes: ["salmon", "citrus", "window"],
    dislikes: ["mushroom"],
    seatingPreferences: ["window", "accessible"],
    visitCount: 6,
    lastVisit: "Jun 18",
    notes: "Celebrating an anniversary. Prefers a quieter table.",
  },
  {
    id: "guest-jordan",
    name: "Jordan Ellis",
    partySize: 2,
    reservationTime: "6:30 PM",
    arrivalTime: null,
    status: "expected",
    allergies: [],
    dietaryNeeds: ["vegan"],
    likes: ["beet", "spicy"],
    dislikes: [],
    seatingPreferences: ["patio"],
    visitCount: 2,
    lastVisit: "Apr 02",
    notes: "Ask whether patio weather is comfortable.",
  },
  {
    id: "guest-priya",
    name: "Priya Shah",
    partySize: 5,
    reservationTime: "7:00 PM",
    arrivalTime: "6:11 PM",
    status: "waiting",
    allergies: ["sesame"],
    dietaryNeeds: [],
    likes: ["chicken", "chef specials"],
    dislikes: ["fish"],
    seatingPreferences: ["accessible"],
    visitCount: 1,
    lastVisit: null,
    notes: "One guest uses a wheelchair.",
  },
  {
    id: "guest-noah",
    name: "Noah Williams",
    partySize: 3,
    reservationTime: "5:45 PM",
    arrivalTime: "5:39 PM",
    status: "seated",
    allergies: [],
    dietaryNeeds: [],
    likes: ["steak", "chocolate"],
    dislikes: [],
    seatingPreferences: [],
    visitCount: 4,
    lastVisit: "May 21",
    notes: "Business dinner; keep pacing efficient.",
  },
];

export const demoOrders: Order[] = [
  {
    id: "order-noah",
    guestId: "guest-noah",
    tableId: "t3",
    status: "draft",
    lines: [],
    guestNotes: "",
    createdAt: "2026-08-09T21:39:00.000Z",
  },
];

export const fallbackDishContext =
  "Seasonal preparation details are unavailable. Confirm ingredients and substitutions with the kitchen before describing them to a guest.";
